# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Función para unir una matriz con un vector y que este ultimo quede
#' en la ultima columna de la matriz.
#' @param NumericMatriz de tipo nxm.
#' @param NumericVector de largo n.
#' @export
#' @examples
#' matriz_aleatoria <- function(n) {
#'matriz <- matrix(round(runif(n^2, 0, 1), 1), nrow = n, ncol = n)
#'  for (i in 1:n) {
#'    matriz[i, i] <- 1
#'  }
#'  return(matriz)
#'    }
#' set.seed(123)
#' A<- matrizAleatoria(3)
#' B<- c(1, 2, 3)
#' #Donde A es
#'#      [,1] [,2] [,3]
#'#[1,]  1.0  0.9  0.5
#'#[2,]  0.8  1.0  0.9
#'#[3,]  0.4  0.0  1.0
#'
#'
#' cbind_rcpp(A,B)
#' #Da como resultado
#'#      [,1] [,2] [,3] [,4]
#'#[1,]  1.0  0.9  0.9     1
#'#[2,]  1.0  1.0  0.9     2
#'#[3,]  0.5  0.4  1.0     3
#'
cbind_rcpp <- function(matrix_1, vector_1) {
    .Call(`_TallerEv1_cbind_rcpp`, matrix_1, vector_1)
}

#' Función para obtener el maxmimo de los minimos valores entre
#' las columna de una matriz y las filas de otra matriz, ambas cuadraticas
#'
#' @param NumericMatriz de tipo nxn.
#' @param NumericMatriz de tipo nxn.
#' @export
#' @examples
#' matriz_aleatoria <- function(n) {
#'matriz <- matrix(round(runif(n^2, 0, 1), 1), nrow = n, ncol = n)
#'  for (i in 1:n) {
#'    matriz[i, i] <- 1
#'  }
#'  return(matriz)
#'    }
#' set.seed(123)
#' A<- matrizAleatoria(3)
#' B<- matrizAleatoria(3)
#' #Donde A es
#'#      [,1] [,2] [,3]
#'#[1,]  1.0  0.9  0.5
#'#[2,]  0.8  1.0  0.9
#'#[3,]  0.4  0.0  1.0
#'#y B es
#'#     [,1] [,2] [,3]
#'#[1,]  1.0  0.7  0.9
#'#[2,]  1.0  1.0  0.2
#'#[3,]  0.5  0.1  1.0
#'
#'
#' maxmin_cpp(A,B)
#' #Da como resultado
#'#      [,1] [,2] [,3]
#'#[1,]  1.0  0.9  0.9
#'#[2,]  1.0  1.0  0.9
#'#[3,]  0.5  0.4  1.0
#'
maxmin_cpp <- function(matrix_1, matrix_2) {
    .Call(`_TallerEv1_maxmin_cpp`, matrix_1, matrix_2)
}

#' Función para realizar una multiplicacion matricial procesada en C++
#' @param NumericMatriz de tipo mxn.
#' @param NumericMatriz de tipo nxc.
#' @export
#' @examples
#' matriz_aleatoria <- function(n) {
#'matriz <- matrix(round(runif(n^2, 0, 1), 1), nrow = n, ncol = n)
#'  for (i in 1:n) {
#'    matriz[i, i] <- 1
#'  }
#'  return(matriz)
#'    }
#' set.seed(123)
#' A<- matrizAleatoria(3)
#' B<- matrizAleatoria(3)
#' #Donde A es
#'#      [,1] [,2] [,3]
#'#[1,]  1.0  0.9  0.5
#'#[2,]  0.8  1.0  0.9
#'#[3,]  0.4  0.0  1.0
#'
#'#Donde B es
#'#      [,1] [,2] [,3]
#'#[1,]  1.0  0.9  0.5
#'#[2,]  1.0  1.0  0.9
#'#[3,]  0.5  0.1  1.
#'
#'
#' mult_matrix_rcpp(A,B)
#' #Da como resultado
#'#      [,1] [,2] [,3]
#'#[1,]  2.15 1.65 1.58
#'#[2,]  2.25 1.65 1.82
#'#[3,]  0.90 0.38 1.36
#'
mult_matrix_rcpp <- function(matrix_1, matrix_2) {
    .Call(`_TallerEv1_mult_matrix_rcpp`, matrix_1, matrix_2)
}

#' Función para unir una matriz con un vector y que este ultimo quede
#' en la ultima fila de la matriz.
#' @param NumericMatriz de tipo mxn.
#' @param NumericVector de largo n.
#' @export
#' @examples
#' matriz_aleatoria <- function(n) {
#'matriz <- matrix(round(runif(n^2, 0, 1), 1), nrow = n, ncol = n)
#'  for (i in 1:n) {
#'    matriz[i, i] <- 1
#'  }
#'  return(matriz)
#'    }
#' set.seed(123)
#' A<- matrizAleatoria(3)
#' B<- c(1, 2, 3)
#' #Donde A es
#'#      [,1] [,2] [,3]
#'#[1,]  1.0  0.9  0.5
#'#[2,]  0.8  1.0  0.9
#'#[3,]  0.4  0.0  1.0
#'
#'
#' rbind_rcpp(A,B)
#' #Da como resultado
#'#      [,1] [,2] [,3]
#'#[1,]  1.0  0.9  0.9
#'#[2,]  1.0  1.0  0.9
#'#[3,]  0.5  0.4  1.0
#'#[4,]    1   2     3
#'
rbind_rcpp <- function(matrix_1, vector_1) {
    .Call(`_TallerEv1_rbind_rcpp`, matrix_1, vector_1)
}

#' Función para encontrar el o los máximos valores de una matrix, esta retorna en un data frame las posiciones (las posiciones estan pensadas para comenzar desde 1 como funciona en R).
#' @param NumericMatriz de tipo mxn.
#' @export
#' @examples
#' matriz_aleatoria <- function(n) {
#'matriz <- matrix(round(runif(n^2, 0, 1), 1), nrow = n, ncol = n)
#'  for (i in 1:n) {
#'    matriz[i, i] <- 1
#'  }
#'  return(matriz)
#'    }
#' set.seed(123)
#' A<- matrizAleatoria(3)
#' #Donde A es
#'#      [,1] [,2] [,3]
#'#[1,]  1.0  0.9  0.5
#'#[2,]  0.8  1.0  0.9
#'#[3,]  0.4  0.0  1.0
#'
#'
#' wich_max_rcpp(A)
#' #Da como resultado
#'#  pos_max_fila pos_max_columna
#'#1            1               1
#'#2            2               2
#'#3            3               3
#'
wich_max_rcpp <- function(matrix_1) {
    .Call(`_TallerEv1_wich_max_rcpp`, matrix_1)
}

#' Función para encontrar el o los minimos valores de una matriz, esta retorna en un data frame las posiciones (las posiciones estan pensadas para comenzar desde 1 como funciona en R).
#' @param NumericMatriz de tipo mxn.
#' @export
#' @examples
#' matriz_aleatoria <- function(n) {
#'matriz <- matrix(round(runif(n^2, 0, 1), 1), nrow = n, ncol = n)
#'  for (i in 1:n) {
#'    matriz[i, i] <- 1
#'  }
#'  return(matriz)
#'    }
#' set.seed(123)
#' A<- matrizAleatoria(3)
#' #Donde A es
#'#      [,1] [,2] [,3]
#'#[1,]  1.0  0.9  0.5
#'#[2,]  0.8  1.0  0.9
#'#[3,]  0.4  0.0  1.0
#'
#'
#' wich_min_rcpp(A)
#' #Da como resultado
#'#  pos_max_fila pos_max_columna
#'#1            3               2
#'
wich_min_rcpp <- function(matrix_1) {
    .Call(`_TallerEv1_wich_min_rcpp`, matrix_1)
}

